DROP TABLE IF EXISTS t_article;

CREATE TABLE t_article (
art_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
art_title VARCHAR(100) NOT NULL,
art_content VARCHAR(2000) NOT NULL
) ENGINE=innodb CHARACTER SET utf8 COLLATE utf8_unicode_ci;